apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.secret }}
      name: wow-api-clientid
      property: projects.droptimizer.wowApiClientId
    - key: {{ .Values.secret }}
      name: wow-api-secret
      property: projects.droptimizer.wowApiSecret
    - key: {{ .Values.secret }}
      name: raidbots-cookie
      property: projects.droptimizer.raidbotsCookie
