apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  backendType: systemManager
  data:
    - key: {{ .Values.secret }}
      name: wow-api-clientid
      property: wowApiClientId
    - key: {{ .Values.secret }}
      name: wow-api-secret
      property: wowApiSecret
    - key: {{ .Values.secret }}
      name: raidbots-cookie
      property: raidbotsCookie
